name: CI / Automated Pull Request 

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'
      - 'dev'
      - 'prod'
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pusher.name != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        id: create-pr
        uses: offensive-vk/auto-pr-action@master
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
          destination_branch: 'master'
          title: '🐹 - (${{ github.event.head_commit.message }})'
          reviewers: 'offensive-vk'
          labels: 'bot,automated,hamster,pull-request'
          assignees: 'TheHamsterBot'
          draft: false
          body: |
            ## This Pull Request Was Automated by [Hamster [bot]](https://github.com/TheHamsterBot)

            > [!NOTE]
            > Workflow Trigger: ${{ github.event_name }} event at ${{ github.ref_name }}
            > Details of Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            - Author: @TheHamsterBot
            - Branch: master (base) / ${{ github.ref_name }} (head)
            - Commit: ${{ github.sha }}
            - Workflow Path: ${{ github.workflow }}
            - Pusher Details: ${{ github.event.pusher.name }} - ${{ github.event.pusher.email }}
            - Most Recent Commit: ${{ github.event.head_commit.message }}

            ---

            Thanks.
            Your Hamster 🐹 <code>PF78VAPPKLZ2</code>
        
      - name: Save PR Number in ENV
        run:
          echo "PR_NUMBER=${{ steps.create-pr.outputs.pr_number }}" >> $GITHUB_ENV; echo "${{ env.PR_NUMBER }}"