name: CI / Docker

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          docker build -t awesomedevops:${{ github.sha }} .