name: CI / Docker - Build Image

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Docker Daemon (macOS only)
        if: matrix.os == 'macos-latest'
        run: |
          dockerd &
          docker system info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t awesome-devops:${{ github.sha }} .
