name: Create GPG Key and Sign Commits

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: "Commit message"
        required: true
        default: "Signed commit with generated GPG key."

jobs:
  sign_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Generate GPG key
        id: generate_gpg_key
        run: |
          GPG_KEY_NAME="Hamster [bot]"
          GPG_KEY_EMAIL="TheHamsterBot@outlook.com"
          GPG_KEY_PASSPHRASE="${{ secrets.GPG_PASSPHRASE }}"

          # Generate GPG key batch file
          cat > gen-key-script <<EOF
          %no-protection
          Key-Type: default
          Key-Length: 4096
          Subkey-Type: default
          Name-Real: $GPG_KEY_NAME
          Name-Email: $GPG_KEY_EMAIL
          Expire-Date: 0
          %commit
          EOF

          # Generate GPG key
          gpg --batch --generate-key gen-key-script

          # Get the fingerprint of the generated key
          GPG_FINGERPRINT=$(gpg --list-secret-keys --keyid-format LONG "$GPG_KEY_EMAIL" | grep "sec" | awk '{print $2}' | awk -F/ '{print $2}')
          
          GPG_KEY=$(gpg --export --armor --output gpg-key.asc)
          echo "GPG_KEY=$GPG_KEY" >> $GITHUB_ENV
          
          # Export key ID for later steps
          echo "GPG_FINGERPRINT=$GPG_FINGERPRINT" >> $GITHUB_ENV

      - name: Configure Git for GPG signing
        run: |
          GPG_FINGERPRINT=${{ env.GPG_FINGERPRINT }}
          git config --global user.signingkey $GPG_FINGERPRINT
          git config --global commit.gpgSign true
          git config --global user.name "Hamster [bot]"
          git config --global user.email "TheHamsterBot@outlook.com"
          git config --global gpg.program gpg

      - name: Add GPG Key to GitHub Account
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADD_GPG_KEY: ${{ env.GPG_KEY }}
        
        run: |
          curl -X PATCH \
          https://api.github.com/users/TheHamsterBot/gpg_keys \
          -H 'Authorization: Bearer ${GITHUB_TOKEN}' \
          -H 'Content-Type: application/json' \
          -d '{"gpg_keys": [{"key": "${ADD_GPG_KEY}"]}'
          
      - name: Create a change (e.g., create a file)
        run: |
          echo "This is a signed commit" > signed-file.txt
          git add signed-file.txt

      - name: Commit the change with GPG signature
        run: |
          git commit -S -m "${{ github.event.inputs.commit_message }}"

      - name: Push the changes to the repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD
