name: CI / Bulk Actions Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync-auto-user-activity:
    name: Auto User Activity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-User-Activity || exit 0
          mkdir -p Auto-User-Activity

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-user-activity.git Auto-User-Activity
          cd Auto-User-Activity
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-user-activity'
          github-token: ${{ secrets.BOT_TOKEN }}

  sync-auto-commit-push:
    name: Auto Commit Push
    needs: [sync-auto-user-activity]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-Commit-Push || exit 0
          mkdir -p Auto-Commit-Push

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-commit-push.git Auto-Commit-Push
          cd Auto-Commit-Push
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-commit-push'
          github-token: ${{ secrets.BOT_TOKEN }}

  sync-auto-issue:
    name: Auto Issue Action
    runs-on: ubuntu-latest
    needs: [sync-auto-commit-push]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-Issue || exit 0
          mkdir -p Auto-Issue

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-issue.git Auto-Issue
          cd Auto-Issue
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-issue'
          github-token: ${{ secrets.BOT_TOKEN }}

  sync-auto-pr:
    name: Auto Pull Request
    needs: [sync-auto-issue]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-Pull-Request || exit 0
          mkdir -p Auto-Pull-Request

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-pull-request.git Auto-Pull-Request
          cd Auto-Pull-Request
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-pull-request'
          github-token: ${{ secrets.BOT_TOKEN }}

  sync-auto-update-quote:
    name: Auto Update Quote
    needs: [sync-auto-pr]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-Update-Quote || exit 0
          mkdir -p Auto-Update-Quote

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-update-quote.git Auto-Update-Quote
          cd Auto-Update-Quote
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-update-quote'
          github-token: ${{ secrets.BOT_TOKEN }}

  sync-auto-repo-sync:
    name: Auto Repo Sync
    needs: [sync-auto-update-quote]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-Repo-Sync || exit 0
          mkdir -p Auto-Repo-Sync

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-repo-sync.git Auto-Repo-Sync
          cd Auto-Repo-Sync
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-repo-sync'
          github-token: ${{ secrets.BOT_TOKEN }}

  sync-auto-add-project:
    name: Auto Add Project
    needs: [sync-auto-repo-sync]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-Add-Project || exit 0
          mkdir -p Auto-Add-Project

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-add-project.git Auto-Add-Project
          cd Auto-Add-Project
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-add-project'
          github-token: ${{ secrets.BOT_TOKEN }}

  sync-auto-stats:
    name: Auto Stats
    needs: [sync-auto-add-project]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-Stats || exit 0
          mkdir -p Auto-Stats

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-stats.git Auto-Stats
          cd Auto-Stats
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-stats'
          github-token: ${{ secrets.BOT_TOKEN }}

  sync-auto-label:
    name: Auto Labeler
    needs: [sync-auto-stats]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-Label || exit 0
          mkdir -p Auto-Label

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-label.git Auto-Label
          cd Auto-Label
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-label'
          github-token: ${{ secrets.BOT_TOKEN }}

  sync-auto-translate:
    name: Auto Translate
    needs: [sync-auto-label]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-Translate || exit 0
          mkdir -p Auto-Translate

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-translate.git Auto-Translate
          cd Auto-Translate
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-translate'
          github-token: ${{ secrets.BOT_TOKEN }}

  sync-auto-pr-action:
    name: Auto PR Action
    needs: [sync-auto-translate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-PR-Action || exit 0
          mkdir -p Auto-PR-Action

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-pr-action.git Auto-PR-Action
          cd Auto-PR-Action
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-pr-action'
          github-token: ${{ secrets.BOT_TOKEN }}

  sync-auto-contributions:
    name: Auto Contributions
    needs: [sync-auto-pr-action]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf Auto-Contributions || exit 0
          mkdir -p Auto-Contributions

      - name: Fetch Upstream Changes
        run: |
          git clone --depth 1 https://github.com/offensive-vk/auto-contributions.git Auto-Contributions
          cd Auto-Contributions
          rm -rf .git/
          cd ..

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v7
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-contributions'
          github-token: ${{ secrets.BOT_TOKEN }}

  finish-repo-sync:
    runs-on: ubuntu-latest
    name: Report Successful Syncing
    needs: [sync-auto-contributions]
    steps:
      - name: Goodbye
        run: | 
           echo -e "Perfect! All the Remote Repositories are done syncing. \n\tHave a Good Day!"
