name: Mirror Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-auto-pr:
    name: Auto Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create Directory
        run: mkdir -p AwesomeTesting || exit 0

      - name: Begin Sync
        run: |
          git clone --mirror https://github.com/offensive-vk/auto-pull-request.git temp_repo
          rsync -a temp_repo/ AwesomeTesting/
          rm -rf temp_repo

      - name: Commit and Push
        uses: offensive-vk/auto-commit-push@v5
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master'
          message: 'Remote Repo Sync - auto-pull-request'
          github-token: ${{ secrets.BOT_TOKEN }} 
