name: Sign Stuff

on:
  workflow_dispatch:

jobs:
  begin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Import GPG Key
        id: data
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
          trust_level: 5

      # Optional: Verify GPG key
      - name: Verify GPG Key
        run: |
          gpg --list-secret-keys --keyid-format LONG
          git config --list

      # Set the correct GPG key fingerprint (optional if using a specific key)
      - name: Set GPG Signing Key
        run: git config --global user.signingkey ${{ steps.data.outputs.fingerprint }}

      - name: Break something
        run: echo "Key--=-=->${{ steps.data.outputs.fingerprint }}" > key.txt

      - name: Commit and Push changes
        uses: offensive-vk/auto-commit-push@v6
        with: 
          name: 'Hamster [bot]'
          email: 'TheHamsterBot@outlook.com'
          branch: 'master' 
          message: 'Remote Commit by Bot.'
          github-token: ${{ secrets.BOT_TOKEN }}
